sonar.projectKey=willphamsg_mdcs-cp
sonar.organization=willphamsg

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/test/**,**/*.stories.ts,**/sslcertificate/**,**/tools/**,**/identification/**
sonar.coverage.exclusions=**/*.spec.ts,**/test/**,**/*.stories.ts

sonar.sourceEncoding=UTF-8
