sonar.projectKey=willphamsg_mdcs-cp
sonar.organization=willphamsg

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/test/**,**/*.stories.ts,**/sslcertificate/**,**/tools/**,**/identification/**
sonar.coverage.exclusions=**/*.spec.ts,**/test/**,**/*.stories.ts,**/main.ts,**/polyfills.ts,**/environments/**

# Karma/Istanbul LCOV produced by `pnpm run test:coverage:ci`
sonar.javascript.lcov.reportPaths=coverage/lta-btds-gui/lcov.info

sonar.sourceEncoding=UTF-8
